
//package functional;
import java.util.stream.*;
import java.util.function.*;
import java.util.*;


public class Week9Exercises {
	public static void main(String[] args) {
		List<Integer> ints = Arrays.asList(5, 3, 25, 7, 63, 4, 73, 42, 72, 3, 64, 6, 0, -34, 2, -521, 32);
		List<String> strings = Arrays.asList("HELLO", "aPpLe", "WORLD", "carrot", "JAVA", "cow", "fig", "PROGRAMMING");
		List<Double> doubles = List.of(32.1, 2.76, 3.0, 1.45, 89.2);
		List<String> namesList = List.of("Mary", "Jane");
		List<Integer> ints2 = Arrays.asList(5, -3, 15, 7, 3);

		/*
		 * 1. Use a Predicate to filter a list of integers, keeping only those that are
		 * divisible by 3.
		 */

		Predicate<Integer> divBy3 = (n) -> (n%3 == 0);
		List<Integer> integers = ints.stream().filter(divBy3).collect(Collectors.toList());

		System.out.println("Input:" + ints);
		System.out.println("output:" + integers);
		System.out.println();

		/*
		 * 2. Create a Function that takes a double and returns the whole number
		 * portion.
		 */
		Function<Double, Integer> intPart = (n) -> ((int)Math.floor(n));
		
		List<Integer> wholeParts = doubles.stream().map(intPart).collect(Collectors.toList());

		System.out.println("Input:" + doubles);
		System.out.println("Output: " + wholeParts);
		System.out.println();

		/* 3. Use a Consumer to print each string in a list in lowercase. */

		Consumer<String> print = (s) -> {System.out.println(s.toLowerCase());};

		System.out.println(strings);
		strings.stream().forEach(print);
		System.out.println();

		/*
		 * 4. Write code that filters a list of integers to keep only those greater than
		 * 50 and divisible by 3. Combine multiple predicates and resuse your predicate
		 * from 1.
		 */
		
		List<Integer> integers2 = ints.stream().filter(n -> n>50).filter(divBy3).collect(Collectors.toList());

		System.out.println("Input:" + ints);
		System.out.println("Output: " + integers2);
		System.out.println();

		/*
		 * 5.  Write code to square each number in a list of integers and then calculate the
		 * sum of all squared values.
		 */

		int squareSum = ints2.stream().collect(Collectors.summingInt(n -> n*n));

		System.out.println("Input:" + ints2);
		System.out.println("Output(Sum of squares): " + squareSum);
		System.out.println();

		/*
		 *6. Write a function to add a prefix "Hello, " to a given string. Apply it to a
		 * list of names.
		 */

		List<String> helloNames = namesList.stream().map(n -> ("Hello, " + n)).collect(Collectors.toList());

		System.out.println("Input: " + namesList);
		System.out.println("Output: " + helloNames);
		System.out.println();

		/*
		 * 7. Write a function that converts a number to its cube.
		 * Write a function that converts a number to a string prefixed by "Result: ".
		 * Chain these functions and
		 * apply them to a list of numbers.
		 */
		
		Function<Integer, Integer> cube = (n) -> (n*n*n);
		Function<Integer, String> stringify = (n) -> ("Result: " + Integer.toString(n));
		List<String> result = ints2.stream().map(cube).collect(Collectors.mapping(stringify, Collectors.toList()));

		System.out.println("Input:" + ints2);
		System.out.println("Output (cubed and prefixed with Result): " + result);
		System.out.println();
		/**
		 * 8. Write a Supplier to generate random integers between 1 and 100.
		 * Call the supplier 10 times and create a list of the the generated values.
		 */

		Supplier<Integer> randomInt = () -> (1+(int)(Math.random()*100));
		List<Integer> intList = new ArrayList<>();
		for (int i = 0; i < 10; i++) {
			intList.add(randomInt.get());
		}

		System.out.println("List generated by Supplier: " + intList);
		System.out.println();

		/**
		 * 9.  Create a BiFunction that takes two strings
		 * and returns their concatenation with a space in between.
		 * Use it on pairs of strings.
		 * https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html
		 */
		
		BiFunction<String, String, String> concatSpace = (a,b) -> (a + " " + b);

		System.out.println("Input: {Hello, Dear}");
		System.out.println("Output: " + concatSpace.apply("Hello", "Dear"));

		List<String> strList2 = List.of("Would", "this", "darkness", "ever", "lift?");
		String newStr = strList2.stream().reduce("", concatSpace, (u1,u2) -> concatSpace.apply(u1,u2));

		System.out.println("Input: " + strList2);
		System.out.println("Output: " + newStr);
		System.out.println();

		/**
		 * 10. Write a method that takes a list of strings and a Predicate<String> as
		 * arguments.
		 * The method should return a new list containing only the strings that satisfy
		 * the predicate. Test it with:
		 * (a) Strings that start with "P",
		 * (b) Strings longer than 4 characters.
		 */
	
		Predicate<String> startP = (s) -> (s.toLowerCase().charAt(0) == 'p');
		Predicate<String> longer4 = (s) -> (s.length() > 4);

		List<String> list3= List.of("amy", "Peter", "Pam", "Paul", "Neela", "Porter" );		
		System.out.println("InputList: "+list3); 

		List<String> list3Filtered = filterStrings(list3, startP);
		System.out.println("Filtered List: "+ list3Filtered);

		list3Filtered = filterStrings(list3, longer4);
		System.out.println("Filtered List: " + list3Filtered);

		System.out.println();

	}

	//Method for q10
	static List<String> filterStrings(List<String> l, Predicate<String> p) {
		return l.stream().filter(p).collect(Collectors.toList());
	}

}